# Generated by Django 5.0.1 on 2026-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preset', models.CharField(choices=[('teal_slate', 'Teal & Slate (Default)'), ('warm_coral', 'Warm Coral & Amber'), ('emerald_gold', 'Emerald & Gold'), ('ocean_blue', 'Ocean Blue & Sand'), ('rose_charcoal', 'Rose & Charcoal'), ('indigo_amber', 'Indigo & Amber'), ('custom', 'Custom (use fields below)')], default='teal_slate', help_text="Pick a preset palette, or choose 'Custom' to set your own hex values.", max_length=30)),
                ('custom_primary', models.CharField(blank=True, default='', help_text='Primary color hex (e.g. #0d9488). Only used with Custom preset.', max_length=7)),
                ('custom_secondary', models.CharField(blank=True, default='', help_text='Secondary color hex (e.g. #475569). Only used with Custom preset.', max_length=7)),
                ('custom_accent', models.CharField(blank=True, default='', help_text='Accent color hex (e.g. #d97706). Only used with Custom preset.', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Theme',
                'verbose_name_plural': 'Site Themes',
            },
        ),
    ]
