# Generated by Django 5.0.1 on 2026-09-09 07:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitetheme_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_model', models.CharField(choices=[('buyer_pays_all', 'Option A: Zero-Deduction Seller (Buyer Covers 5% Escrow Fee + Gateway Fee)'), ('split_50_50', 'Option B: 50/50 Escrow Split (Buyer Pays 2.5% Escrow Fee + Gateway Fee, Seller Pays 2.5% Commission)')], default='buyer_pays_all', help_text='Active fee model. Switch between Option A (100% Buyer Covered) and Option B (50/50 Split).', max_length=32)),
                ('buyer_escrow_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Escrow & Buyer Protection Fee % charged to the buyer at checkout.', max_digits=5)),
                ('seller_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission % deducted from the seller payout upon escrow release.', max_digits=5)),
                ('pass_gateway_fee_to_buyer', models.BooleanField(default=True, help_text='When enabled, payment processing gateway fee (Monnify) is passed to the buyer at checkout.')),
                ('estimated_gateway_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Estimated payment gateway processing fee % (default: 1.50%).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Platform Fee Setting',
                'verbose_name_plural': 'Platform Fee Settings',
            },
        ),
    ]
