#!/usr/bin/env bash
set -e

echo "==> Starting Railway Production Startup Script for MultiShopNG..."

# Robust manage.py location discovery
if [ -f "/app/project/backend/manage.py" ]; then
    cd /app/project/backend
elif [ -f "./project/backend/manage.py" ]; then
    cd ./project/backend
elif [ -f "./manage.py" ]; then
    echo "==> Already in backend directory: $(pwd)"
else
    MANAGE_PATH=$(find /app / -name "manage.py" 2>/dev/null | head -n 1)
    if [ -n "$MANAGE_PATH" ]; then
        cd "$(dirname "$MANAGE_PATH")"
    fi
fi

echo "==> Working Directory: $(pwd)"

# Ensure DJANGO_SECRET_KEY is present
if [ -z "$DJANGO_SECRET_KEY" ] && [ -z "$SECRET_KEY" ]; then
    export DJANGO_SECRET_KEY="railway-prod-key-$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9')"
    echo "==> Auto-generated runtime DJANGO_SECRET_KEY for security."
elif [ -n "$SECRET_KEY" ] && [ -z "$DJANGO_SECRET_KEY" ]; then
    export DJANGO_SECRET_KEY="$SECRET_KEY"
fi

# Ensure ALLOWED_HOSTS includes Railway domains if not specified
if [ -z "$ALLOWED_HOSTS" ]; then
    export ALLOWED_HOSTS="*,localhost,127.0.0.1,.railway.app,.up.railway.app,multishopng.com"
fi

if [ -z "$DJANGO_SETTINGS_MODULE" ]; then
    export DJANGO_SETTINGS_MODULE="ecommerce.settings.prod"
fi

echo "==> Reconciling Database Migration Dependencies..."
python -c "
import os, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', '${DJANGO_SETTINGS_MODULE:-ecommerce.settings.prod}')
django.setup()
from django.db import connection
try:
    with connection.cursor() as cursor:
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS django_migrations (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                app character varying(255) NOT NULL,
                name character varying(255) NOT NULL,
                applied timestamp with time zone NOT NULL
            );
        ''')
        cursor.execute('''
            INSERT INTO django_migrations (app, name, applied)
            SELECT 'contenttypes', '0001_initial', CURRENT_TIMESTAMP
            WHERE NOT EXISTS (SELECT 1 FROM django_migrations WHERE app = 'contenttypes' AND name = '0001_initial');
            INSERT INTO django_migrations (app, name, applied)
            SELECT 'contenttypes', '0002_touch_inconsistent_content_types', CURRENT_TIMESTAMP
            WHERE NOT EXISTS (SELECT 1 FROM django_migrations WHERE app = 'contenttypes' AND name = '0002_touch_inconsistent_content_types');
        ''')
        auth_migs = [
            '0001_initial', '0002_alter_permission_name_max_length', '0003_alter_user_email_max_length',
            '0004_alter_user_username_opts', '0005_alter_user_last_login_null', '0006_require_contenttypes_0002',
            '0007_alter_validators_add_error_messages', '0008_alter_user_username_max_length',
            '0009_alter_user_last_name_max_length', '0010_alter_group_name_max_length',
            '0011_update_proxy_permissions', '0012_alter_user_first_name_max_length'
        ]
        for am in auth_migs:
            cursor.execute(f'''
                INSERT INTO django_migrations (app, name, applied)
                SELECT 'auth', '{am}', CURRENT_TIMESTAMP
                WHERE NOT EXISTS (SELECT 1 FROM django_migrations WHERE app = 'auth' AND name = '{am}');
            ''')
        cursor.execute('''
            INSERT INTO django_migrations (app, name, applied)
            SELECT 'accounts', '0001_initial', CURRENT_TIMESTAMP
            WHERE NOT EXISTS (SELECT 1 FROM django_migrations WHERE app = 'accounts' AND name = '0001_initial');
        ''')
        print('==> Migration dependency tree reconciled successfully.')
except Exception as e:
    print('==> Migration reconciliation note:', e)
" || true

echo "==> Running Full Database Migrations..."
python manage.py migrate --fake-initial --noinput

echo "==> Populating Initial Database Seed Fixtures..."
python manage.py loaddata seed_data.json || echo "Notice: Seed data already loaded or skipped."

echo "==> Collecting Static Files..."
python manage.py collectstatic --noinput || echo "Warning: Collectstatic had warnings"

PORT_TO_USE="${PORT:-8000}"
echo "==> Launching Gunicorn WSGI Server on port ${PORT_TO_USE}..."
exec gunicorn ecommerce.wsgi:application --bind "0.0.0.0:${PORT_TO_USE}" --workers 3 --timeout 120
