# Generated by Django 5.0.1 on 2026-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('bank_transfer', 'Bank transfer')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_transfer', 'Awaiting bank transfer'), ('processing', 'Processing'), ('captured', 'Captured'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partial_refund', 'Partially refunded')], db_index=True, default='pending', max_length=24),
        ),
    ]
