# Generated by Django 5.0.1 on 2026-08-04 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordergroup_commission_fee'),
        ('payments', '0002_alter_payment_provider_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(choices=[('not_received', 'Item not received'), ('wrong_item', 'Wrong item received'), ('damaged', 'Item arrived damaged'), ('not_as_described', 'Item not as described'), ('changed_mind', 'Changed my mind'), ('other', 'Other')], max_length=24)),
                ('description', models.TextField(help_text='Detailed description of the issue.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from the admin when approving or rejecting.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='orders.ordergroup')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_refund_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_re_status_9d8b07_idx')],
            },
        ),
    ]
