# Generated by Django 5.0.1 on 2026-08-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_add_refund_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paystack", "Paystack"),
                    ("monnify", "Monnify (Moniepoint)"),
                    ("bank_transfer", "Bank transfer"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
