# Generated by Django 5.0.1 on 2026-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_order_alter_payment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paystack_enabled', models.BooleanField(default=True, help_text='Whether Paystack payment gateway is active for checkouts and subscriptions.')),
                ('monnify_enabled', models.BooleanField(default=True, help_text='Whether Monnify (Moniepoint) payment gateway is active for checkouts and subscriptions.')),
                ('default_provider', models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify')], default='monnify', help_text='Default preferred gateway when both are active.', max_length=20)),
            ],
            options={
                'verbose_name': 'Payment Gateway Setting',
                'verbose_name_plural': 'Payment Gateway Settings',
            },
        ),
    ]
