# Generated by Django 5.0.1 on 2026-07-10 03:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('hero', 'Hero'), ('featured_products', 'Featured products'), ('product_grid', 'Product grid'), ('category_showcase', 'Category showcase'), ('banner', 'Banner'), ('rich_text', 'Rich text'), ('gallery', 'Gallery'), ('testimonials', 'Testimonials'), ('newsletter', 'Newsletter'), ('spacer', 'Spacer')], max_length=32)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SectionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('button', 'Button'), ('product', 'Product reference'), ('video', 'Video')], max_length=32)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='shops.layoutsection')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True, validators=[django.core.validators.RegexValidator(message='Slugs may only contain lowercase letters, numbers and hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='shops/banners/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('enable_product_listings', models.BooleanField(default=True)),
                ('enable_custom_orders', models.BooleanField(default=False)),
                ('enable_reviews', models.BooleanField(default=True)),
                ('enable_contact', models.BooleanField(default=True)),
                ('enable_shipping', models.BooleanField(default=False)),
                ('enable_social_links', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='draft', max_length=16)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShopLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact')], default='home', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='shops.shop')),
            ],
        ),
        migrations.AddField(
            model_name='layoutsection',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='shops.shoplayout'),
        ),
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShopStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=16)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #1A2B3C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('secondary_color', models.CharField(default='#10B981', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #1A2B3C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #1A2B3C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #1A2B3C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('surface_color', models.CharField(default='#F9FAFB', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #1A2B3C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('text_color', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #1A2B3C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('muted_text_color', models.CharField(default='#6B7280', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #1A2B3C.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('heading_font', models.CharField(default='Inter', max_length=120)),
                ('body_font', models.CharField(default='Inter', max_length=120)),
                ('base_font_size', models.PositiveSmallIntegerField(default=16)),
                ('border_radius', models.PositiveSmallIntegerField(default=8, help_text='Corner radius in px.')),
                ('button_style', models.CharField(default='solid', max_length=20)),
                ('layout_style', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('magazine', 'Magazine')], default='modern', max_length=20)),
                ('product_card_style', models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact'), ('overlay', 'Overlay'), ('detailed', 'Detailed')], default='standard', max_length=20)),
                ('dark_mode_enabled', models.BooleanField(default=False)),
                ('extra_tokens', models.JSONField(blank=True, default=dict)),
                ('custom_css', models.TextField(blank=True, help_text='Advanced: sanitised custom CSS scoped to the storefront.')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='shops.shop')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['status', 'is_verified'], name='shops_shop_status_ec9717_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['-rating_average'], name='shops_shop_rating__ad1bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['owner', 'status'], name='shops_shop_owner_i_c135c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shoplayout',
            unique_together={('shop', 'page')},
        ),
        migrations.AlterUniqueTogether(
            name='shopreview',
            unique_together={('shop', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='shopstaff',
            unique_together={('shop', 'user')},
        ),
    ]
