# Generated by Django 5.0.1 on 2026-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Owner's custom domain, e.g. 'shop.example.com'. Unique across shops when set.", max_length=253),
        ),
        migrations.AddField(
            model_name='shop',
            name='custom_domain_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending verification'), ('verified', 'Verified'), ('failed', 'Verification failed')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='shop',
            name='custom_domain_verification_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shop',
            name='custom_domain_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
