# Generated by Django 5.0.1 on 2026-07-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_deliverynote_deliveryzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='allow_manual_delivery',
            field=models.BooleanField(default=False, help_text='If true, buyers can choose to arrange delivery manually with the seller (0 fee upfront).'),
        ),
    ]
