# Generated by Django 5.0.1 on 2026-07-18 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_allow_manual_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Government-issued ID or CAC document for manual review.', null=True, upload_to='shops/verification_docs/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='verification_legal_name',
            field=models.CharField(blank=True, help_text='Legal name as it appears on the submitted document.', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about the verification review.'),
        ),
        migrations.AddField(
            model_name='shop',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=16),
        ),
        migrations.AddField(
            model_name='shop',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ShopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('scam', 'Scam / fraud'), ('fake_products', 'Fake or misleading products'), ('non_delivery', 'Never received my order'), ('harassment', 'Harassment or abuse'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='shops.shop')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('shop', 'reporter')},
            },
        ),
    ]
