# Generated by Django 5.0.1 on 2026-07-18 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_verification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Platform commission percentage (e.g. 5.00 for 5%).', max_digits=5),
        ),
    ]
