# Generated by Django 5.0.1 on 2026-07-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='id_number',
            field=models.CharField(blank=True, help_text='Government-issued ID number (e.g. BVN, NIN).', max_length=50),
        ),
    ]
