# Generated by Django 5.0.1 on 2026-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shop_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='template_id',
            field=models.CharField(blank=True, default='', help_text="Machine ID of the premium storefront template, e.g. 'honeyspicy'. Empty = default MultiShop storefront.", max_length=60),
        ),
    ]
