# Generated by Django 5.0.1 on 2026-08-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_alter_shop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='shops/banners/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='shops/logos/'),
        ),
    ]
