# Generated by Django 5.0.1 on 2026-07-18 16:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shops', '0005_shop_verification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='delivery_code',
            field=models.CharField(blank=True, help_text='6-digit code the buyer shares with the seller to confirm delivery.', max_length=6),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='delivery_code_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the seller entered the correct delivery code.', null=True),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='dispute_reason',
            field=models.TextField(blank=True, help_text='Reason provided by the buyer if they open a dispute.'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='escrow_released_at',
            field=models.DateTimeField(blank=True, help_text="When the funds were released to the seller's wallet.", null=True),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='escrow_status',
            field=models.CharField(choices=[('held', 'Held in escrow'), ('released', 'Released to seller'), ('disputed', 'Under dispute'), ('refunded', 'Refunded to buyer')], db_index=True, default='held', max_length=16),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Available balance from released escrow funds.', max_digits=14)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Lifetime earnings from all released orders.', max_digits=14)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total amount withdrawn/paid out.', max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='shops.shop')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('escrow_release', 'Escrow release'), ('withdrawal', 'Withdrawal'), ('refund_debit', 'Refund debit'), ('adjustment', 'Manual adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after this transaction.', max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='E.g. OrderGroup public_id for escrow releases.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.sellerwallet')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
