# Generated by Django 5.0.1 on 2026-07-18 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordergroup_delivery_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Platform commission deducted from this order group.', max_digits=12),
        ),
    ]
