# Generated by Django 5.0.1 on 2026-08-08 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sellerbankaccount_payoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='logistics_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Platform logistics handling markup collected on shipping.', max_digits=12),
        ),
    ]
