# Generated by Django 5.0.1 on 2026-08-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordergroup_logistics_markup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroup',
            name='escrow_status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('held', 'Held in escrow'), ('released', 'Released to seller'), ('disputed', 'Under dispute'), ('refunded', 'Refunded to buyer')], db_index=True, default='pending', max_length=16),
        ),
    ]
