# Generated by Django 5.0.1 on 2026-08-23 15:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordergroup_escrow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))]),
        ),
    ]
