# Generated by Django 5.0.1 on 2026-09-09 07:14

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escrow_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Escrow & Buyer Protection Fee charged to buyer.', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Payment processing gateway fee (Monnify/Paystack).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
