/**
 * Detailed customization schema for every single storefront template.
 * Defines template-specific fields, image slots, section titles, and styling defaults.
 */
export const TEMPLATE_CUSTOMIZATION_SCHEMAS = {
  honeyspicy: {
    id: 'honeyspicy',
    name: 'Honey Gourmet Template',
    tagline: 'Warm gourmet culinary bakery & restaurant template',
    hero: {
      hasWelcomePrefix: true,
      welcomePrefixLabel: 'Welcome Prefix (e.g. "Welcome to", "Introducing")',
      welcomePrefixDefault: 'Welcome to',
      hasHeadline: true,
      headlineLabel: 'Main Store Headline Title',
      hasSubtitle: true,
      subtitleLabel: 'Hero Tagline / Catchphrase',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Primary Button Text',
      ctaPrimaryDefault: 'Order Now',
      hasCtaSecondary: true,
      ctaSecondaryLabel: 'Secondary Button Text',
      ctaSecondaryDefault: 'View Menu',
      imageSlots: [
        { key: 'hero_image_1', label: 'Showcase Bubble 1 (Top Float)', desc: 'Upper circular floating treat image', default: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80' },
        { key: 'hero_image_2', label: 'Showcase Bubble 2 (Center Main)', desc: 'Large center circular floating dish image', default: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80' },
        { key: 'hero_image_3', label: 'Showcase Bubble 3 (Bottom Float)', desc: 'Lower circular floating pastry image', default: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=400&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: true,
      featuredTitleLabel: 'Signature Treats Section Heading',
      featuredTitleDefault: 'Our Signature Treats',
      hasFeaturedSubtitle: true,
      featuredSubtitleLabel: 'Signature Treats Subtitle',
      featuredSubtitleDefault: 'Explore our most popular and delicious creations',
      hasCatalogTitle: true,
      catalogTitleLabel: 'Menu / Catalog Heading',
      catalogTitleDefault: 'Explore Our Menu',
      categoriesSubtitleDefault: 'Handcrafted to perfection with premium quality culinary ingredients',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'What Our Happy Customers Say',
    },
    features: {
      hasFeaturesBanner: true,
      bannerTitle: '4 Culinary Highlight Cards',
      defaultCards: [
        { key1: 'feature1_title', val1: 'Fresh Daily', key2: 'feature1_desc', val2: 'All of our treats are made fresh every morning' },
        { key1: 'feature2_title', val1: 'Quality Ingredients', key2: 'feature2_desc', val2: 'We use only the finest natural ingredients' },
        { key1: 'feature3_title', val1: 'Fast Delivery', key2: 'feature3_desc', val2: 'Doorstep delivery within 30 minutes' },
        { key1: 'feature4_title', val1: 'Secure Checkout', key2: 'feature4_desc', val2: '100% buyer protection via MultiShop' },
      ]
    },
    palettePresets: [
      { name: 'Honey Gold', icon: '🍯', primary_color: '#E5A43B', banner_color: '#E5A43B', background_color: '#FFFDF9', text_color: '#2B1F0C' },
      { name: 'Warm Caramel', icon: '🥐', primary_color: '#D97706', banner_color: '#78350F', background_color: '#FFFBEB', text_color: '#451A03' },
      { name: 'Berry Glaze', icon: '🍓', primary_color: '#BE123C', banner_color: '#881337', background_color: '#FFF1F2', text_color: '#4C0519' },
      { name: 'Dark Mocha', icon: '☕', primary_color: '#78350F', banner_color: '#271B12', background_color: '#FAF8F5', text_color: '#1A120B' },
      { name: 'Pistachio Matcha', icon: '🍵', primary_color: '#15803D', banner_color: '#14532D', background_color: '#F0FDF4', text_color: '#052E16' },
      { name: 'Velvet Vanilla', icon: '🍦', primary_color: '#CA8A04', banner_color: '#422006', background_color: '#FEFCE8', text_color: '#3B1F04' },
    ],
    defaultColors: { primary: '#E5A43B', banner: '#E5A43B', bg: '#FFFDF9', text: '#2B1F0C' },
    defaultFont: 'Poppins',
  },

  minimalist: {
    id: 'minimalist',
    name: 'Studio Minimalist',
    tagline: 'Clean architectural Scandinavian studio aesthetic',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Header Label / Edition Code',
      badgeDefault: 'Architectural Collection // 2026',
      hasHeadline: true,
      headlineLabel: 'Studio Title / Brand Name',
      hasSubtitle: true,
      subtitleLabel: 'Studio Manifesto / Description',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Catalog Explore Button',
      ctaPrimaryDefault: 'Explore Index [01] ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Fig. 01 Studio Architectural Photo', desc: 'Single monochrome product / architectural hero photo on the right', default: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=600&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Catalogue Index Title',
      catalogTitleDefault: '/// CATALOGUE INDEX',
      categoriesSubtitleDefault: 'Functional form, unadorned geometry, and archival materials.',
      hasCatalogSearchPlaceholder: true,
      catalogSearchPlaceholderDefault: 'SEARCH INDEX...',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Critical Reviews & Press Notes',
    },
    features: {
      hasFeaturesBanner: false,
    },
    palettePresets: [
      { name: 'Pure Monochrome', icon: '⬛', primary_color: '#000000', banner_color: '#18181B', background_color: '#FFFFFF', text_color: '#18181B' },
      { name: 'Slate Architecture', icon: '🏛️', primary_color: '#334155', banner_color: '#1E293B', background_color: '#F8FAFC', text_color: '#0F172A' },
      { name: 'Sandpaper Minimal', icon: '📜', primary_color: '#57534E', banner_color: '#292524', background_color: '#FAFAF9', text_color: '#1C1917' },
      { name: 'Obsidian Noir', icon: '🖤', primary_color: '#111827', banner_color: '#030712', background_color: '#F3F4F6', text_color: '#111827' },
      { name: 'Warm Bone', icon: '🦴', primary_color: '#44403C', banner_color: '#78716C', background_color: '#F5F5F4', text_color: '#292524' },
      { name: 'Nordic Steel', icon: '📐', primary_color: '#475569', banner_color: '#0F172A', background_color: '#F1F5F9', text_color: '#0F172A' },
    ],
    defaultColors: { primary: '#000000', banner: '#111827', bg: '#FFFFFF', text: '#111827' },
    defaultFont: 'Space Grotesk',
  },

  cyberpunk: {
    id: 'cyberpunk',
    name: 'Neon Cyberpunk',
    tagline: 'Futuristic synthwave storefront with glowing neon HUD',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'System Protocol Header Tag',
      badgeDefault: '/// PROTOCOL_V2.04 // HIGH TECH GEAR',
      hasHeadline: true,
      headlineLabel: 'Cyber Grid Title / Brand',
      hasSubtitle: true,
      subtitleLabel: 'Terminal Subtitle / Mission Log',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Grid Matrix CTA Button',
      ctaPrimaryDefault: 'ACCESS GRID MATRIX ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'HUD Preview Holo-Frame Image', desc: 'Right-side neon bordered cyberpunk showcase visual', default: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Hardware Grid Section Title',
      catalogTitleDefault: '/// HARDWARE_GRID',
      categoriesSubtitleDefault: 'Military-grade cybernetic hardware, neural modules & synthwave peripherals',
      hasCatalogSearchPlaceholder: true,
      catalogSearchPlaceholderDefault: 'SEARCH_SYSTEM...',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: '/// SYSTEM_LOGS // AGENT_FEEDBACK',
    },
    features: {
      hasFeaturesBanner: false,
    },
    palettePresets: [
      { name: 'Neon Synthwave', icon: '⚡', primary_color: '#FF007F', banner_color: '#0D0221', background_color: '#05010D', text_color: '#00F0FF' },
      { name: 'Toxic Matrix', icon: '🟢', primary_color: '#39FF14', banner_color: '#021A04', background_color: '#010B02', text_color: '#39FF14' },
      { name: 'Cyber Blue HUD', icon: '💠', primary_color: '#00F0FF', banner_color: '#001026', background_color: '#000814', text_color: '#E0F2FE' },
      { name: 'Glitch Amethyst', icon: '🔮', primary_color: '#A855F7', banner_color: '#1E0B36', background_color: '#0F051D', text_color: '#F3E8FF' },
      { name: 'Industrial Cyber', icon: '☣️', primary_color: '#F59E0B', banner_color: '#1F1202', background_color: '#0F0901', text_color: '#FEF3C7' },
      { name: 'Laser Crimson', icon: '🚨', primary_color: '#EF4444', banner_color: '#1A0005', background_color: '#0D0003', text_color: '#FEE2E2' },
    ],
    defaultColors: { primary: '#FF007F', banner: '#0D0221', bg: '#05010D', text: '#00F0FF' },
    defaultFont: 'Space Grotesk',
  },

  obsidian: {
    id: 'obsidian',
    name: 'Obsidian Luxe Template',
    tagline: 'Sleek, ultra-modern dark luxury & high-tech storefront',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Luxury Badge Label',
      badgeDefault: 'Exclusive Haute Horlogerie & Fashion',
      hasHeadline: true,
      headlineLabel: 'Hero Main Title',
      hasSubtitle: true,
      subtitleLabel: 'Hero Tagline / Subtitle',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Primary Button',
      ctaPrimaryDefault: 'Discover Collection',
      hasCtaSecondary: true,
      ctaSecondaryLabel: 'Secondary Button',
      ctaSecondaryDefault: 'Explore Catalog',
      imageSlots: [
        { key: 'hero_image_1', label: 'Floating 3D Hero Luxury Asset', desc: 'Featured hero product card render', default: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: true,
      featuredTitleLabel: 'Featured Masterpieces Heading',
      featuredTitleDefault: 'Featured Masterpieces',
      hasFeaturedSubtitle: true,
      featuredSubtitleLabel: 'Featured Masterpieces Subtitle',
      featuredSubtitleDefault: 'Curated selection of our most prestigious releases',
      hasCatalogTitle: true,
      catalogTitleLabel: 'Catalog Title',
      catalogTitleDefault: 'All Masterpieces',
      categoriesSubtitleDefault: 'Explore handcrafted luxury creations and precision-engineered editions',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Client Testimonials',
    },
    features: {
      hasFeaturesBanner: true,
      bannerTitle: '4 Luxury Guarantee Badges',
      defaultCards: [
        { key1: 'feature1_title', val1: 'Authenticity Guaranteed', key2: 'feature1_desc', val2: '100% verified original luxury items' },
        { key1: 'feature2_title', val1: 'Bespoke Packaging', key2: 'feature2_desc', val2: 'Presented in signature handcrafted gift boxes' },
        { key1: 'feature3_title', val1: 'White-Glove Delivery', key2: 'feature3_desc', val2: 'Insured premium doorstep courier service' },
        { key1: 'feature4_title', val1: 'Lifetime Warranty', key2: 'feature4_desc', val2: 'Full coverage on craftsmanship and precision' },
      ]
    },
    palettePresets: [
      { name: 'Violet Obsidian', icon: '🔮', primary_color: '#8B5CF6', banner_color: '#13111C', background_color: '#07090E', text_color: '#F8FAFC' },
      { name: 'Cyan Stealth', icon: '💠', primary_color: '#00F0FF', banner_color: '#0A121E', background_color: '#030712', text_color: '#E0F2FE' },
      { name: 'Rose Gold Noir', icon: '✨', primary_color: '#F43F5E', banner_color: '#1F0C14', background_color: '#0A0306', text_color: '#FFF1F2' },
      { name: 'Platinum Noir', icon: '💎', primary_color: '#E2E8F0', banner_color: '#18181B', background_color: '#09090B', text_color: '#FFFFFF' },
      { name: 'Emerald Velvet', icon: '👑', primary_color: '#10B981', banner_color: '#06281E', background_color: '#03140F', text_color: '#ECFDF5' },
      { name: 'Amber Cognac', icon: '🥃', primary_color: '#F59E0B', banner_color: '#261502', background_color: '#120900', text_color: '#FEF3C7' },
    ],
    defaultColors: { primary: '#8B5CF6', banner: '#13111C', bg: '#07090E', text: '#F8FAFC' },
    defaultFont: 'Plus Jakarta Sans',
  },

  emerald: {
    id: 'emerald',
    name: 'Verdant Organics',
    tagline: 'Deep forest green botanical & organic wellness aesthetic',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Organic Certified Tag',
      badgeDefault: '100% ORGANIC & ETHICAL HARVEST',
      hasHeadline: true,
      headlineLabel: 'Apothecary / Brand Name',
      hasSubtitle: true,
      subtitleLabel: 'Botanical Philosophy',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Apothecary CTA Button',
      ctaPrimaryDefault: 'Shop Herbal Blends 🌿',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Botanical Nature Hero Banner', desc: 'Organic herbs and wellness botanical image', default: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Catalog Section Title',
      catalogTitleDefault: 'Botanical Collection',
      categoriesSubtitleDefault: 'Pure organically sourced botanical extracts and holistic remedies',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Holistic Client Experiences',
    },
    features: {
      hasFeaturesBanner: true,
      bannerTitle: '4 Botanical Guarantees',
      defaultCards: [
        { key1: 'feature1_title', val1: 'Farm Fresh', key2: 'feature1_desc', val2: 'Direct from organic growers' },
        { key1: 'feature2_title', val1: 'Cruelty Free', key2: 'feature2_desc', val2: 'Zero animal testing, 100% vegan' },
        { key1: 'feature3_title', val1: 'Zero Waste', key2: 'feature3_desc', val2: 'Eco-friendly recyclable packaging' },
        { key1: 'feature4_title', val1: 'Wellness', key2: 'feature4_desc', val2: '100% money-back satisfaction guarantee' },
      ]
    },
    palettePresets: [
      { name: 'Forest Apothecary', icon: '🌿', primary_color: '#059669', banner_color: '#022C22', background_color: '#F0FDF4', text_color: '#064E3B' },
      { name: 'Sage & Linen', icon: '🌱', primary_color: '#65A30D', banner_color: '#1A2E05', background_color: '#F7FEE7', text_color: '#365314' },
      { name: 'Tea Tree Mint', icon: '🍃', primary_color: '#10B981', banner_color: '#064E3B', background_color: '#ECFDF5', text_color: '#064E3B' },
      { name: 'Earthy Olive', icon: '🫒', primary_color: '#84CC16', banner_color: '#365314', background_color: '#FEFCE8', text_color: '#422006' },
      { name: 'Eucalyptus Morning', icon: '🌾', primary_color: '#0D9488', banner_color: '#134E4A', background_color: '#F0FDFA', text_color: '#115E59' },
      { name: 'Botanical Gold', icon: '🌼', primary_color: '#CA8A04', banner_color: '#064E3B', background_color: '#FEFCE8', text_color: '#14532D' },
    ],
    defaultColors: { primary: '#059669', banner: '#064E3B', bg: '#F2FBF6', text: '#064E3B' },
    defaultFont: 'Cormorant Garamond',
  },

  royal: {
    id: 'royal',
    name: 'Velvet Royalty',
    tagline: 'Imperial velvet palette with polished gold accents',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Maison Heritage Tag',
      badgeDefault: 'HAUTE HORLOGERIE & JOAILLERIE',
      hasHeadline: true,
      headlineLabel: 'Imperial Title / Maison Name',
      hasSubtitle: true,
      subtitleLabel: 'Prestige Statement',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Acquisition Button',
      ctaPrimaryDefault: 'Acquire Collection ♛',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Imperial Jewelry Showcase Photo', desc: 'Prestige gemstone / timepiece image', default: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Treasury Section Title',
      catalogTitleDefault: 'The Royal Gallery',
      categoriesSubtitleDefault: 'Rare collectibles, fine jewelry, and bespoke prestige acquisitions',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Distinguished Patron Reviews',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Imperial Gold & Velvet', icon: '👑', primary_color: '#C9A84C', banner_color: '#1A1019', background_color: '#120A11', text_color: '#F5E6D3' },
      { name: 'Royal Navy & Gold', icon: '⚜️', primary_color: '#D4AF37', banner_color: '#0A1128', background_color: '#050914', text_color: '#FBF8F0' },
      { name: 'Emerald Crown', icon: '💎', primary_color: '#50C878', banner_color: '#041F14', background_color: '#02100A', text_color: '#E8F5E9' },
      { name: 'Crimson Regent', icon: '🍷', primary_color: '#E11D48', banner_color: '#2B0610', background_color: '#150308', text_color: '#FFF1F2' },
      { name: 'Amethyst Sovereign', icon: '🔮', primary_color: '#C084FC', banner_color: '#2E1065', background_color: '#0F0324', text_color: '#FAF5FF' },
      { name: 'Onyx Palace', icon: '🖤', primary_color: '#F59E0B', banner_color: '#000000', background_color: '#050505', text_color: '#FFFFFF' },
    ],
    defaultColors: { primary: '#D4AF37', banner: '#1A0B2E', bg: '#0A0512', text: '#FDF6E2' },
    defaultFont: 'Cinzel',
  },

  boho: {
    id: 'boho',
    name: 'Terracotta Earth',
    tagline: 'Warm clay, sun-baked terracotta, and artisanal ceramics',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Studio Badge',
      badgeDefault: 'HAND-THROWN IN SMALL BATCHES',
      hasHeadline: true,
      headlineLabel: 'Ceramic Studio Name',
      hasSubtitle: true,
      subtitleLabel: 'Craft Philosophy',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Pottery CTA Button',
      ctaPrimaryDefault: 'Browse Collection ✿',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Handcrafted Pottery Hero Photo', desc: 'Warm clay ceramics image', default: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Studio Catalog Title',
      catalogTitleDefault: '✿ Handpicked Treasures',
      categoriesSubtitleDefault: 'Artisan handcrafted ceramic vessels, woven textiles, and earthen homeware',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Patron Love & Studio Stories',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Terracotta & Clay', icon: '🏺', primary_color: '#C4785A', banner_color: '#5C3828', background_color: '#FAF5EF', text_color: '#4A3225' },
      { name: 'Sunbaked Ochre', icon: '🌾', primary_color: '#D97706', banner_color: '#78350F', background_color: '#FFFBEB', text_color: '#451A03' },
      { name: 'Desert Sand & Sage', icon: '🌵', primary_color: '#84A98C', banner_color: '#354F52', background_color: '#F5F5F0', text_color: '#2F3E46' },
      { name: 'Woven Linen', icon: '🧶', primary_color: '#A27B5C', banner_color: '#3F4E4F', background_color: '#DCD7C9', text_color: '#2C3639' },
      { name: 'Rust & Earthen Ash', icon: '🪵', primary_color: '#9A3412', banner_color: '#431407', background_color: '#FAFAF9', text_color: '#292524' },
      { name: 'Warm Terracotta', icon: '🍂', primary_color: '#C2410C', banner_color: '#7C2D12', background_color: '#FAF5EF', text_color: '#431407' },
    ],
    defaultColors: { primary: '#C2410C', banner: '#7C2D12', bg: '#FAF5EF', text: '#431407' },
    defaultFont: 'Playfair Display',
  },

  popart: {
    id: 'popart',
    name: 'Vibrant Pop Art',
    tagline: 'Electric yellow and hot pink comic neobrutalism layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Drop Badge Label',
      badgeDefault: '💥 100% LOUD & UNAPOLOGETIC!',
      hasHeadline: true,
      headlineLabel: 'Pop Brand Title',
      hasSubtitle: true,
      subtitleLabel: 'Comic Tagline',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Action CTA Button',
      ctaPrimaryDefault: 'EXPLORE DROPS 💥',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Comic Pop Visual Art Card', desc: 'Vibrant pop art collectible showcase image', default: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Vault Title',
      catalogTitleDefault: '/// POP CULTURE VAULT',
      categoriesSubtitleDefault: 'Statement goods, limited designer vinyl art toys, and high-contrast apparel',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: '💥 COLLECTOR FAN REVIEWS 💥',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Pop Comic Magenta', icon: '💥', primary_color: '#EC4899', banner_color: '#06B6D4', background_color: '#FEF08A', text_color: '#000000' },
      { name: 'Warning Pop Yellow', icon: '⚡', primary_color: '#FACC15', banner_color: '#000000', background_color: '#FFFFFF', text_color: '#000000' },
      { name: 'Superhero Comic', icon: '🦸', primary_color: '#EF4444', banner_color: '#2563EB', background_color: '#FFFFFF', text_color: '#000000' },
      { name: 'Toxic Bubblegum', icon: '🍬', primary_color: '#F43F5E', banner_color: '#10B981', background_color: '#FDF2F8', text_color: '#000000' },
      { name: 'Electric Tangerine', icon: '🔥', primary_color: '#F97316', banner_color: '#8B5CF6', background_color: '#FEF9C3', text_color: '#000000' },
      { name: 'Ultra Acid Cyan', icon: '🧪', primary_color: '#06B6D4', banner_color: '#EC4899', background_color: '#FFFFFF', text_color: '#000000' },
    ],
    defaultColors: { primary: '#FACC15', banner: '#EC4899', bg: '#FEF08A', text: '#000000' },
    defaultFont: 'Montserrat',
  },

  retro: {
    id: 'retro',
    name: 'Vintage 70s Vinyl',
    tagline: 'Groovy 1970s warm mustard and burnt orange analog aesthetic',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Vinyl Heritage Tag',
      badgeDefault: '📻 180g Audiophile Pressings & Vintage Gear',
      hasHeadline: true,
      headlineLabel: 'Record Store / Brand Name',
      hasSubtitle: true,
      subtitleLabel: 'Vintage Catchphrase',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Crate Digging Button',
      ctaPrimaryDefault: 'SPIN RECORDS 📻 →',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Vintage Vinyl Turntable Image', desc: 'Warm 70s turntable or vintage gear photo', default: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Vinyl Section Title',
      catalogTitleDefault: '/// VINYL CRATE & RETRO GEAR',
      categoriesSubtitleDefault: 'Original analog pressings, high-fidelity turntable hardware & audio relics',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Audiophile Listening Notes',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: '70s Vinyl Orange', icon: '📻', primary_color: '#EA580C', banner_color: '#78350F', background_color: '#FFFBEB', text_color: '#78350F' },
      { name: 'Mustard & Teal', icon: '🎸', primary_color: '#D97706', banner_color: '#0F766E', background_color: '#FEF3C7', text_color: '#451A03' },
      { name: 'Analog Cassette', icon: '📼', primary_color: '#B45309', banner_color: '#3E1F0A', background_color: '#FAF4EB', text_color: '#291405' },
      { name: 'Sunset Disco', icon: '🪩', primary_color: '#F43F5E', banner_color: '#4C1D95', background_color: '#FFF1F2', text_color: '#581C87' },
      { name: 'Woodgrain Hi-Fi', icon: '🪵', primary_color: '#92400E', banner_color: '#451A03', background_color: '#FFFDF5', text_color: '#451A03' },
      { name: 'Avocado Mid-Century', icon: '🥑', primary_color: '#65A30D', banner_color: '#78350F', background_color: '#FEFCE8', text_color: '#365314' },
    ],
    defaultColors: { primary: '#D97706', banner: '#78350F', bg: '#FFFBEB', text: '#451A03' },
    defaultFont: 'Playfair Display',
  },

  pastel: {
    id: 'pastel',
    name: 'Pastel Dreamscape',
    tagline: 'Soft lavender, peach, and marshmallow confectionery layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Gentle Glow Tag',
      badgeDefault: '✦ Welcome to',
      hasHeadline: true,
      headlineLabel: 'Pastel Store Name',
      hasSubtitle: true,
      subtitleLabel: 'Pastel Whisper',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Pastel Button',
      ctaPrimaryDefault: 'Browse All Items ✦',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Pastel Aesthetic Hero Visual', desc: 'Dreamy soft pastel lifestyle or stationery image', default: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Pastel Confections Title',
      catalogTitleDefault: '✦ All Items',
      categoriesSubtitleDefault: 'Cute stationery, dreamy accessories, and pastel lifestyle confections',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Sweet Community Feedback',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Cotton Candy', icon: '🍬', primary_color: '#F472B6', banner_color: '#C084FC', background_color: '#FDF2F8', text_color: '#4A3560' },
      { name: 'Lavender Milk', icon: '🪻', primary_color: '#A855F7', banner_color: '#818CF8', background_color: '#FAF5FF', text_color: '#3B0764' },
      { name: 'Matcha Cream', icon: '🍵', primary_color: '#34D399', banner_color: '#6EE7B7', background_color: '#F0FDF4', text_color: '#064E3B' },
      { name: 'Peach Smoothie', icon: '🍑', primary_color: '#FB923C', banner_color: '#FCA5A5', background_color: '#FFF7ED', text_color: '#7C2D12' },
      { name: 'Sky Marshmallow', icon: '☁️', primary_color: '#38BDF8', banner_color: '#A78BFA', background_color: '#F0F9FF', text_color: '#0C4A6E' },
      { name: 'Buttercream Dream', icon: '🧁', primary_color: '#FBBF24', banner_color: '#F472B6', background_color: '#FEFCE8', text_color: '#451A03' },
    ],
    defaultColors: { primary: '#F472B6', banner: '#C084FC', bg: '#FDF2F8', text: '#4A3560' },
    defaultFont: 'Quicksand',
  },

  industrial: {
    id: 'industrial',
    name: 'Industrial Forge',
    tagline: 'Raw concrete, blueprint gridlines, and precision fabrication tools',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Engineering Spec Badge',
      badgeDefault: '// HEAVY DUTY INDUSTRIAL SPECS',
      hasHeadline: true,
      headlineLabel: 'Forge Name / Foundry Title',
      hasSubtitle: true,
      subtitleLabel: 'Technical Spec Summary',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Access Inventory Button',
      ctaPrimaryDefault: 'ACCESS INVENTORY ⚙',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Industrial Machinery / Blueprint Image', desc: 'Precision machine tool or raw iron hardware photo', default: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Manifest Title',
      catalogTitleDefault: '[INVENTORY MANIFEST]',
      categoriesSubtitleDefault: 'Heavy machinery parts, precision tools, raw alloys, and workshop supplies',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: '// FIELD_TEST_REPORTS & CLIENT_SPECS',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Amber Forge', icon: '⚙️', primary_color: '#F59E0B', banner_color: '#1C1C1C', background_color: '#121212', text_color: '#E0D8C8' },
      { name: 'Hazard Safety Yellow', icon: '🚧', primary_color: '#EAB308', banner_color: '#27272A', background_color: '#09090B', text_color: '#FAFAFA' },
      { name: 'Machined Steel Cyan', icon: '🔩', primary_color: '#06B6D4', banner_color: '#1E293B', background_color: '#0F172A', text_color: '#F1F5F9' },
      { name: 'Foundry Rust Red', icon: '🏗️', primary_color: '#DC2626', banner_color: '#262626', background_color: '#171717', text_color: '#EDEDED' },
      { name: 'Cast Iron Bronze', icon: '🪨', primary_color: '#CA8A04', banner_color: '#18181B', background_color: '#09090B', text_color: '#F5F5F4' },
      { name: 'Industrial Blueprint', icon: '📐', primary_color: '#3B82F6', banner_color: '#0C4A6E', background_color: '#082F49', text_color: '#E0F2FE' },
    ],
    defaultColors: { primary: '#F59E0B', banner: '#1C1C1C', bg: '#121212', text: '#E0D8C8' },
    defaultFont: 'Chakra Petch',
  },
  zenith: {
    id: 'zenith',
    name: 'Zenith Modern',
    tagline: 'High performance data-driven SaaS & enterprise storefront',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Enterprise Badge',
      badgeDefault: 'ENTERPRISE SCALE ECOSYSTEM',
      hasHeadline: true,
      headlineLabel: 'Platform Title',
      hasSubtitle: true,
      subtitleLabel: 'Solution Tagline',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Solutions CTA',
      ctaPrimaryDefault: 'Explore Solutions ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Tech Hardware & Device Photo', desc: 'Clean high-performance device showcase image', default: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Inventory Heading',
      catalogTitleDefault: 'Product Inventory & Solutions',
      categoriesSubtitleDefault: 'Mission-critical hardware, enterprise components, and dev tools',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Enterprise Case Studies & Metrics',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Indigo SaaS', icon: '🚀', primary_color: '#4F46E5', banner_color: '#1E293B', background_color: '#0F172A', text_color: '#E2E8F0' },
      { name: 'Cyber Blue', icon: '⚡', primary_color: '#0284C7', banner_color: '#0C4A6E', background_color: '#082F49', text_color: '#F0F9FF' },
      { name: 'Emerald Cloud', icon: '🟢', primary_color: '#10B981', banner_color: '#064E3B', background_color: '#022C22', text_color: '#ECFDF5' },
      { name: 'Violet Quantum', icon: '🔮', primary_color: '#7C3AED', banner_color: '#2E1065', background_color: '#0F051D', text_color: '#F5F3FF' },
      { name: 'Slate Light', icon: '💼', primary_color: '#2563EB', banner_color: '#1E293B', background_color: '#F8FAFC', text_color: '#0F172A' },
      { name: 'Obsidian Pulse', icon: '🖤', primary_color: '#38BDF8', banner_color: '#18181B', background_color: '#09090B', text_color: '#F8FAFC' },
    ],
    defaultColors: { primary: '#4F46E5', banner: '#1E293B', bg: '#0F172A', text: '#E2E8F0' },
    defaultFont: 'Inter',
  },

  monochrome: {
    id: 'monochrome',
    name: 'Monochrome Dark',
    tagline: 'Ultra-contrast black & white gallery aesthetic',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Noir Edition Tag',
      badgeDefault: 'NOIR COLLECTION // EDITION 01',
      hasHeadline: true,
      headlineLabel: 'Monochrome Brand Name',
      hasSubtitle: true,
      subtitleLabel: 'Minimalist Summary',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'View Index Button',
      ctaPrimaryDefault: 'View Catalog ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Noir Studio Visual Photo', desc: 'Monochrome high-contrast design photo', default: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Index Title',
      catalogTitleDefault: 'Curated Noir Index',
      categoriesSubtitleDefault: 'High-contrast monochrome objects, stark shadows, and timeless silhouette design',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Critical Journal Entries',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Pure Noir', icon: '🖤', primary_color: '#FFFFFF', banner_color: '#18181B', background_color: '#09090B', text_color: '#F4F4F5' },
      { name: 'Charcoal Minimal', icon: '⬛', primary_color: '#E4E4E7', banner_color: '#27272A', background_color: '#18181B', text_color: '#FAFAFA' },
      { name: 'Silver Slate', icon: '🪨', primary_color: '#94A3B8', banner_color: '#1E293B', background_color: '#0F172A', text_color: '#F1F5F9' },
      { name: 'Inverted Whiteout', icon: '⚪', primary_color: '#000000', banner_color: '#E4E4E7', background_color: '#FFFFFF', text_color: '#09090B' },
      { name: 'Warm Noir', icon: '☕', primary_color: '#D6D3D1', banner_color: '#292524', background_color: '#1C1917', text_color: '#FAF8F5' },
      { name: 'Graphite Metal', icon: '📐', primary_color: '#CBD5E1', banner_color: '#334155', background_color: '#0B0F19', text_color: '#FFFFFF' },
    ],
    defaultColors: { primary: '#FFFFFF', banner: '#18181B', bg: '#09090B', text: '#F4F4F5' },
    defaultFont: 'Outfit',
  },

  artisan: {
    id: 'artisan',
    name: 'The Artisan Gazette',
    tagline: 'Editorial broadsheet newspaper print layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Masthead Sub-Header Tag',
      badgeDefault: 'EST. 1892 // DAILY ARTISAN DISPATCH',
      hasHeadline: true,
      headlineLabel: 'Gazette Masthead Name',
      hasSubtitle: true,
      subtitleLabel: 'Editorial Opening Column',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Dispatch CTA Button',
      ctaPrimaryDefault: 'Read Classifieds ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Front Page Editorial Photo', desc: 'Vintage print or newspaper story photo', default: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Classifieds Title',
      catalogTitleDefault: 'Classifieds & Curated Goods',
      categoriesSubtitleDefault: 'Printed chronicles of rare local commodities and bespoke goods',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Letters to the Editor & Reader Acclaim',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Parchment & Sepia', icon: '📜', primary_color: '#8B7355', banner_color: '#2D2D2D', background_color: '#FBF8F0', text_color: '#2D2D2D' },
      { name: 'Newsprint Black', icon: '📰', primary_color: '#1C1917', banner_color: '#44403C', background_color: '#FAFAF9', text_color: '#1C1917' },
      { name: 'Vintage Oak', icon: '🪵', primary_color: '#78350F', banner_color: '#451A03', background_color: '#FEFCE8', text_color: '#451A03' },
      { name: 'Antiquarian Leather', icon: '📖', primary_color: '#9A3412', banner_color: '#3F2012', background_color: '#F5EBE1', text_color: '#2D1808' },
      { name: 'Inkwell Navy', icon: '🖋️', primary_color: '#1E3A8A', banner_color: '#172554', background_color: '#F8FAFC', text_color: '#0F172A' },
      { name: 'Bespoke Tweed', icon: '🧶', primary_color: '#65A30D', banner_color: '#365314', background_color: '#F7FEE7', text_color: '#1A2E05' },
    ],
    defaultColors: { primary: '#8B7355', banner: '#2D2D2D', bg: '#FBF8F0', text: '#2D2D2D' },
    defaultFont: 'Playfair Display',
  },

  futura: {
    id: 'futura',
    name: 'Futura Cyber Matrix',
    tagline: 'Sci-fi holographic HUD and neon cyan matrix grid',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'System Kernel Badge',
      badgeDefault: 'SYSTEM BOOT // V3.88 KERNEL ACTIVE',
      hasHeadline: true,
      headlineLabel: 'Matrix Station Name',
      hasSubtitle: true,
      subtitleLabel: 'Command Subtitle',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Matrix CTA Button',
      ctaPrimaryDefault: 'Initialize Matrix ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Holographic Matrix Visual', desc: 'Cyber futuristic matrix hero render', default: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Matrix Title',
      catalogTitleDefault: 'Cybernetic Device Matrix',
      categoriesSubtitleDefault: 'Neural implants, quantum coprocessors, and sub-light network modules',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: '/// TERMINAL_DATASTREAM_REVIEWS',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Neon Cyan HUD', icon: '💠', primary_color: '#00F0FF', banner: '#030712', banner_color: '#030712', background_color: '#020617', text_color: '#38BDF8' },
      { name: 'Plasma Violet', icon: '🔮', primary_color: '#C084FC', banner_color: '#1E0B36', background_color: '#070110', text_color: '#E9D5FF' },
      { name: 'Matrix Emerald', icon: '🟢', primary_color: '#22C55E', banner_color: '#022C22', background_color: '#010F0A', text_color: '#86EFAC' },
      { name: 'Solar Flare Orange', icon: '☀️', primary_color: '#FB923C', banner_color: '#431407', background_color: '#0F0300', text_color: '#FDBA74' },
      { name: 'Glitch Hot Pink', icon: '⚡', primary_color: '#F43F5E', banner_color: '#2E020F', background_color: '#080004', text_color: '#FECDD3' },
      { name: 'Laser Amber', icon: '☣️', primary_color: '#FBBF24', banner_color: '#2E1802', background_color: '#090500', text_color: '#FDE68A' },
    ],
    defaultColors: { primary: '#00F0FF', banner: '#030712', bg: '#020617', text: '#38BDF8' },
    defaultFont: 'Space Grotesk',
  },

  lookbook: {
    id: 'lookbook',
    name: 'Editorial Lookbook',
    tagline: 'High-fashion runway and editorial haute couture layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Season Runway Tag',
      badgeDefault: 'AUTUMN / WINTER EDITORIAL LOOKBOOK',
      hasHeadline: true,
      headlineLabel: 'Fashion House / Brand Title',
      hasSubtitle: true,
      subtitleLabel: 'Runway Statement',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Lookbook CTA Button',
      ctaPrimaryDefault: 'View Lookbook ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Runway High Fashion Image', desc: 'Haute couture editorial model photo', default: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Collection Title',
      catalogTitleDefault: 'Runway Capsule Collection',
      categoriesSubtitleDefault: 'Hand-tailored garments, limited-release silhouettes, and artisanal couture',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Fashion Press & Critic Acclaim',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Vogue Noir', icon: '🖤', primary_color: '#FFFFFF', banner_color: '#111827', background_color: '#000000', text_color: '#F3F4F6' },
      { name: 'Chic Bordeaux', icon: '🍷', primary_color: '#F43F5E', banner_color: '#4C0519', background_color: '#120005', text_color: '#FFE4E6' },
      { name: 'Cashmere Camel', icon: '🧥', primary_color: '#D97706', banner_color: '#451A03', background_color: '#FAF6F0', text_color: '#291405' },
      { name: 'Silk Ivory', icon: '🕊️', primary_color: '#18181B', banner_color: '#E4E4E7', background_color: '#FAFAFA', text_color: '#18181B' },
      { name: 'Midnight Velvet', icon: '🌌', primary_color: '#A78BFA', banner_color: '#1E1B4B', background_color: '#08061C', text_color: '#EDE9FE' },
      { name: 'Emerald Couture', icon: '💎', primary_color: '#34D399', banner_color: '#064E3B', background_color: '#021C14', text_color: '#D1FAE5' },
    ],
    defaultColors: { primary: '#FFFFFF', banner: '#111827', bg: '#000000', text: '#F3F4F6' },
    defaultFont: 'Syne',
  },

  bazaar: {
    id: 'bazaar',
    name: 'Bazaar Marketplace',
    tagline: 'Multi-category marketplace with category pills and badges',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Marketplace Verification Tag',
      badgeDefault: '100% VERIFIED SELLERS & BUYER PROTECTED',
      hasHeadline: true,
      headlineLabel: 'Marketplace Name',
      hasSubtitle: true,
      subtitleLabel: 'Marketplace Slogan',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Browse Button',
      ctaPrimaryDefault: 'Browse Marketplace ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Marketplace Banner / Hero Image', desc: 'Wide banner showcase visual', default: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Categories Title',
      catalogTitleDefault: 'Marketplace Goods & Stalls',
      categoriesSubtitleDefault: 'Discover thousands of verified products from independent merchants',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Buyer & Vendor Experiences',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Sunset Spice', icon: '🌶️', primary_color: '#FF6B35', banner_color: '#FF6B35', background_color: '#F7F7F7', text_color: '#333333' },
      { name: 'Ocean Market', icon: '🌊', primary_color: '#0284C7', banner_color: '#0369A1', background_color: '#F0F9FF', text_color: '#0C4A6E' },
      { name: 'Market Green', icon: '🥬', primary_color: '#16A34A', banner_color: '#15803D', background_color: '#F0FDF4', text_color: '#14532D' },
      { name: 'Royal Purple', icon: '👑', primary_color: '#7C3AED', banner_color: '#6D28D9', background_color: '#FAF5FF', text_color: '#3B0764' },
      { name: 'Bold Crimson', icon: '🛍️', primary_color: '#E11D48', banner_color: '#BE123C', background_color: '#FFF1F2', text_color: '#4C0519' },
      { name: 'Dark Bazaar', icon: '🏮', primary_color: '#FF6B35', banner_color: '#1F2937', background_color: '#111827', text_color: '#F9FAFB' },
    ],
    defaultColors: { primary: '#FF6B35', banner: '#FF6B35', bg: '#F7F7F7', text: '#333333' },
    defaultFont: 'Inter',
  },

  timeline: {
    id: 'timeline',
    name: 'Museum Archive',
    tagline: 'Curatorial museum artifact archive and exhibition layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Exhibition Hall Badge',
      badgeDefault: 'PERMANENT CURATORIAL EXHIBITION',
      hasHeadline: true,
      headlineLabel: 'Museum / Archive Title',
      hasSubtitle: true,
      subtitleLabel: 'Curatorial Foreword',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Exhibition Tour Button',
      ctaPrimaryDefault: 'Tour Archive ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Historical Artifact Hero Image', desc: 'Museum sculpture or relic artifact photo', default: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Exhibition Section Title',
      catalogTitleDefault: 'Permanent Exhibition & Artifacts',
      categoriesSubtitleDefault: 'Chronological timeline of rare artifacts, preserved specimens, and historical relics',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Curatorial Feedback & Visitor Reviews',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Gallery Gold', icon: '🏛️', primary_color: '#C9A84C', banner_color: '#1C1917', background_color: '#0C0A09', text_color: '#E7E5E4' },
      { name: 'Marble Classical', icon: '🗿', primary_color: '#78716C', banner_color: '#292524', background_color: '#FAFAF9', text_color: '#1C1917' },
      { name: 'Bronze Antiquity', icon: '🏺', primary_color: '#D97706', banner_color: '#451A03', background_color: '#1A0C02', text_color: '#FEF3C7' },
      { name: 'Obsidian Archive', icon: '🖤', primary_color: '#A8A29E', banner_color: '#0C0A09', background_color: '#000000', text_color: '#FFFFFF' },
      { name: 'Royal Patina', icon: '⚜️', primary_color: '#2DD4BF', banner_color: '#134E4A', background_color: '#041B18', text_color: '#CCFBF1' },
      { name: 'Terracotta Relic', icon: '🏺', primary_color: '#EA580C', banner_color: '#431407', background_color: '#170600', text_color: '#FFEDD5' },
    ],
    defaultColors: { primary: '#C9A84C', banner: '#1C1917', bg: '#0C0A09', text: '#E7E5E4' },
    defaultFont: 'Cinzel',
  },

  department: {
    id: 'department',
    name: 'Department Store',
    tagline: 'Traditional multi-aisle retail department store',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Storefront Service Tag',
      badgeDefault: 'PREMIER RETAIL DEPARTMENT STORE',
      hasHeadline: true,
      headlineLabel: 'Department Store Name',
      hasSubtitle: true,
      subtitleLabel: 'Store Catchphrase',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Aisles CTA Button',
      ctaPrimaryDefault: 'Shop Department ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Department Retail Banner Image', desc: 'Clean department store showroom photo', default: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Aisles Section Title',
      catalogTitleDefault: 'Department Catalog & Aisles',
      categoriesSubtitleDefault: 'Full retail catalogue across home, fashion, electronics, and daily essentials',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Customer Satisfaction Ratings',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Navy & Silver', icon: '🏬', primary_color: '#1B3A5C', banner_color: '#1B3A5C', background_color: '#FFFFFF', text_color: '#333333' },
      { name: 'Classic Emerald', icon: '🌲', primary_color: '#065F46', banner_color: '#047857', background_color: '#F0FDF4', text_color: '#064E3B' },
      { name: 'Modern Indigo', icon: '🛍️', primary_color: '#4338CA', banner_color: '#3730A3', background_color: '#EEF2FF', text_color: '#1E1B4B' },
      { name: 'Burgundy Retail', icon: '🍷', primary_color: '#881337', banner_color: '#9F1239', background_color: '#FFF1F2', text_color: '#4C0519' },
      { name: 'Warm Charcoal', icon: '🏢', primary_color: '#374151', banner_color: '#1F2937', background_color: '#F9FAFB', text_color: '#111827' },
      { name: 'Golden Department', icon: '🌟', primary_color: '#B45309', banner_color: '#92400E', background_color: '#FFFBEB', text_color: '#451A03' },
    ],
    defaultColors: { primary: '#1B3A5C', banner: '#1B3A5C', bg: '#FFFFFF', text: '#333333' },
    defaultFont: 'Inter',
  },

  polaroid: {
    id: 'polaroid',
    name: 'Polaroid Memories',
    tagline: 'Nostalgic instant polaroid photo snap album layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Film Snap Tag',
      badgeDefault: 'INSTANT MEMORIES & HANDMADE SNAPS',
      hasHeadline: true,
      headlineLabel: 'Polaroid Studio Title',
      hasSubtitle: true,
      subtitleLabel: 'Nostalgia Catchphrase',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Flip Album Button',
      ctaPrimaryDefault: 'Flip Memories ➔',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Featured Polaroid Photo Snap', desc: 'Instant film polaroid print photo', default: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Snaps Title',
      catalogTitleDefault: 'Instant Polaroid Photo Snaps',
      categoriesSubtitleDefault: 'Captured film memories, custom print sets, and nostalgic lifestyle keepsakes',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Handwritten Customer Notes',
    },
    features: { hasFeaturesBanner: false },
    palettePresets: [
      { name: 'Sepia Film Snap', icon: '📷', primary_color: '#8B6F55', banner_color: '#4A3728', background_color: '#FAF6F0', text_color: '#4A3728' },
      { name: 'Vintage Warm Cream', icon: '🎞️', primary_color: '#9A3412', banner_color: '#78350F', background_color: '#FEFCE8', text_color: '#451A03' },
      { name: 'Monochrome Film', icon: '📼', primary_color: '#44403C', banner_color: '#1C1917', background_color: '#F5F5F4', text_color: '#292524' },
      { name: 'Pastel Filter', icon: '🌸', primary_color: '#F472B6', banner_color: '#C084FC', background_color: '#FFF1F2', text_color: '#500724' },
      { name: 'Cyanotype Blue', icon: '🟦', primary_color: '#0284C7', banner_color: '#0C4A6E', background_color: '#F0F9FF', text_color: '#082F49' },
      { name: 'Olive Polaroid', icon: '🫒', primary_color: '#65A30D', banner_color: '#365314', background_color: '#F7FEE7', text_color: '#1A2E05' },
    ],
    defaultColors: { primary: '#8B6F55', banner: '#4A3728', bg: '#FAF6F0', text: '#4A3728' },
    defaultFont: 'Caveat',
  },

  default: {
    id: 'default',
    name: 'Default Storefront',
    tagline: 'Standard clean MultiShop storefront for all sellers',
    hero: {
      hasWelcomePrefix: true,
      welcomePrefixLabel: 'Welcome Prefix (e.g. "Welcome to")',
      welcomePrefixDefault: 'Welcome to',
      hasHeadline: true,
      headlineLabel: 'Store Headline / Store Name',
      hasSubtitle: true,
      subtitleLabel: 'Store Tagline / Bio',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Primary Button Text',
      ctaPrimaryDefault: 'Explore Catalog',
      hasCtaSecondary: true,
      ctaSecondaryLabel: 'Secondary Button Text',
      ctaSecondaryDefault: 'About Us',
      imageSlots: [
        { key: 'banner_url', label: 'Store Banner Image', desc: 'Hero banner background image displayed at the top of your store', default: '' },
      ],
    },
    sections: {
      hasFeaturedTitle: true,
      featuredTitleLabel: 'Featured Products Title',
      featuredTitleDefault: 'Featured Products',
      hasFeaturedSubtitle: true,
      featuredSubtitleLabel: 'Featured Subtitle',
      featuredSubtitleDefault: 'Handpicked favorites and top selling items',
      hasCatalogTitle: true,
      catalogTitleLabel: 'Product Catalog Heading',
      catalogTitleDefault: 'All Products',
      categoriesSubtitleDefault: 'Browse our full collection of verified products',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Customer Reviews',
    },
    features: {
      hasFeaturesBanner: true,
      bannerTitle: '4 Store Highlight Cards',
      defaultCards: [
        { key1: 'feature1_title', val1: 'Authentic Quality', key2: 'feature1_desc', val2: '100% verified original quality goods' },
        { key1: 'feature2_title', val1: 'Fast Delivery', key2: 'feature2_desc', val2: 'Swift doorstep shipping nationwide' },
        { key1: 'feature3_title', val1: 'Secure Escrow', key2: 'feature3_desc', val2: 'Protected payments with delivery codes' },
        { key1: 'feature4_title', val1: 'Dedicated Support', key2: 'feature4_desc', val2: 'Quick response and customer care' },
      ]
    },
    palettePresets: [
      { name: 'MultiShop Blue', icon: '🔵', primary_color: '#2563EB', banner_color: '#1E40AF', background_color: '#FFFFFF', text_color: '#111827' },
      { name: 'Emerald Green', icon: '🌲', primary_color: '#059669', banner_color: '#065F46', background_color: '#F0FDF4', text_color: '#064E3B' },
      { name: 'Sunset Amber', icon: '🌅', primary_color: '#D97706', banner_color: '#78350F', background_color: '#FFFBEB', text_color: '#451A03' },
      { name: 'Royal Purple', icon: '👑', primary_color: '#7C3AED', banner_color: '#5B21B6', background_color: '#FAF5FF', text_color: '#3B0764' },
      { name: 'Crimson Rose', icon: '🌹', primary_color: '#E11D48', banner_color: '#9F1239', background_color: '#FFF1F2', text_color: '#4C0519' },
      { name: 'Charcoal Minimal', icon: '⬛', primary_color: '#1F2937', banner_color: '#111827', background_color: '#F9FAFB', text_color: '#111827' },
    ],
    defaultColors: { primary: '#2563EB', banner: '#1E40AF', bg: '#FFFFFF', text: '#111827' },
    defaultFont: 'Inter',
  },
}

export function getTemplateSchema(templateId) {
  if (!templateId || templateId === 'default') {
    return TEMPLATE_CUSTOMIZATION_SCHEMAS.default || TEMPLATE_CUSTOMIZATION_SCHEMAS.honeyspicy
  }
  return TEMPLATE_CUSTOMIZATION_SCHEMAS[templateId] || TEMPLATE_CUSTOMIZATION_SCHEMAS.default || TEMPLATE_CUSTOMIZATION_SCHEMAS.honeyspicy
}
