/**
 * Detailed customization schema for every single storefront template.
 * Defines template-specific fields, image slots, section titles, and styling defaults.
 */
export const TEMPLATE_CUSTOMIZATION_SCHEMAS = {
  honeyspicy: {
    id: 'honeyspicy',
    name: 'Honey Gourmet Template',
    tagline: 'Warm gourmet culinary bakery & restaurant template',
    hero: {
      hasWelcomePrefix: true,
      welcomePrefixLabel: 'Welcome Prefix (e.g. "Welcome to", "Introducing")',
      welcomePrefixDefault: 'Welcome to',
      hasHeadline: true,
      headlineLabel: 'Main Store Headline Title',
      hasSubtitle: true,
      subtitleLabel: 'Hero Tagline / Catchphrase',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Primary Button Text',
      ctaPrimaryDefault: 'Order Now',
      hasCtaSecondary: true,
      ctaSecondaryLabel: 'Secondary Button Text',
      ctaSecondaryDefault: 'View Menu',
      imageSlots: [
        { key: 'hero_image_1', label: 'Showcase Bubble 1 (Top Float)', desc: 'Upper circular floating treat image', default: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80' },
        { key: 'hero_image_2', label: 'Showcase Bubble 2 (Center Main)', desc: 'Large center circular floating dish image', default: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80' },
        { key: 'hero_image_3', label: 'Showcase Bubble 3 (Bottom Float)', desc: 'Lower circular floating pastry image', default: 'https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=400&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: true,
      featuredTitleLabel: 'Signature Treats Section Heading',
      featuredTitleDefault: 'Our Signature Treats',
      hasFeaturedSubtitle: true,
      featuredSubtitleLabel: 'Signature Treats Subtitle',
      featuredSubtitleDefault: 'Explore our most popular and delicious creations',
      hasCatalogTitle: true,
      catalogTitleLabel: 'Menu / Catalog Heading',
      catalogTitleDefault: 'Explore Our Menu',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'What Our Happy Customers Say',
    },
    features: {
      hasFeaturesBanner: true,
      bannerTitle: '4 Culinary Highlight Cards',
      defaultCards: [
        { key1: 'feature1_title', val1: 'Fresh Daily', key2: 'feature1_desc', val2: 'All of our treats are made fresh every morning' },
        { key1: 'feature2_title', val1: 'Quality Ingredients', key2: 'feature2_desc', val2: 'We use only the finest natural ingredients' },
        { key1: 'feature3_title', val1: 'Fast Delivery', key2: 'feature3_desc', val2: 'Doorstep delivery within 30 minutes' },
        { key1: 'feature4_title', val1: 'Secure Checkout', key2: 'feature4_desc', val2: '100% buyer protection via MultiShop Escrow' },
      ]
    },
    defaultColors: { primary: '#E5A43B', banner: '#E5A43B', bg: '#FFFDF9', text: '#2B1F0C' },
    defaultFont: 'Poppins',
  },

  minimalist: {
    id: 'minimalist',
    name: 'Studio Minimalist',
    tagline: 'Clean architectural Scandinavian studio aesthetic',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Header Label / Edition Code',
      badgeDefault: 'Architectural Collection // 2026',
      hasHeadline: true,
      headlineLabel: 'Studio Title / Brand Name',
      hasSubtitle: true,
      subtitleLabel: 'Studio Manifesto / Description',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Catalog Explore Button',
      ctaPrimaryDefault: 'Explore Index [01] ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Fig. 01 Studio Architectural Photo', desc: 'Single monochrome product / architectural hero photo on the right', default: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=600&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Catalogue Index Title',
      catalogTitleDefault: '/// CATALOGUE INDEX',
      hasCatalogSearchPlaceholder: true,
      catalogSearchPlaceholderDefault: 'SEARCH INDEX...',
    },
    features: {
      hasFeaturesBanner: false,
    },
    defaultColors: { primary: '#000000', banner: '#111827', bg: '#FFFFFF', text: '#111827' },
    defaultFont: 'Space Grotesk',
  },

  cyberpunk: {
    id: 'cyberpunk',
    name: 'Neon Cyberpunk',
    tagline: 'Futuristic synthwave storefront with glowing neon HUD',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'System Protocol Header Tag',
      badgeDefault: '/// PROTOCOL_V2.04 // HIGH TECH GEAR',
      hasHeadline: true,
      headlineLabel: 'Cyber Grid Title / Brand',
      hasSubtitle: true,
      subtitleLabel: 'Terminal Subtitle / Mission Log',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Grid Matrix CTA Button',
      ctaPrimaryDefault: 'ACCESS GRID MATRIX ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'HUD Preview Holo-Frame Image', desc: 'Right-side neon bordered cyberpunk showcase visual', default: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Hardware Grid Section Title',
      catalogTitleDefault: '/// HARDWARE_GRID',
      hasCatalogSearchPlaceholder: true,
      catalogSearchPlaceholderDefault: 'SEARCH_SYSTEM...',
    },
    features: {
      hasFeaturesBanner: false,
    },
    defaultColors: { primary: '#FF007F', banner: '#0D0221', bg: '#05010D', text: '#00F0FF' },
    defaultFont: 'Space Grotesk',
  },

  obsidian: {
    id: 'obsidian',
    name: 'Obsidian Luxe Template',
    tagline: 'Sleek, ultra-modern dark luxury & high-tech storefront',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Luxury Badge Label',
      badgeDefault: 'Exclusive Haute Horlogerie & Fashion',
      hasHeadline: true,
      headlineLabel: 'Hero Main Title',
      hasSubtitle: true,
      subtitleLabel: 'Hero Tagline / Subtitle',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Primary Button',
      ctaPrimaryDefault: 'Discover Collection',
      hasCtaSecondary: true,
      ctaSecondaryLabel: 'Secondary Button',
      ctaSecondaryDefault: 'Explore Catalog',
      imageSlots: [
        { key: 'hero_image_1', label: 'Floating 3D Hero Luxury Asset', desc: 'Featured hero product card render', default: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: true,
      featuredTitleLabel: 'Featured Masterpieces Heading',
      featuredTitleDefault: 'Featured Masterpieces',
      hasFeaturedSubtitle: true,
      featuredSubtitleLabel: 'Featured Masterpieces Subtitle',
      featuredSubtitleDefault: 'Curated selection of our most prestigious releases',
      hasCatalogTitle: true,
      catalogTitleLabel: 'Catalog Title',
      catalogTitleDefault: 'All Masterpieces',
      hasTestimonialsTitle: true,
      testimonialsTitleDefault: 'Client Testimonials',
    },
    features: {
      hasFeaturesBanner: true,
      bannerTitle: '4 Luxury Guarantee Badges',
      defaultCards: [
        { key1: 'feature1_title', val1: 'Authenticity Guaranteed', key2: 'feature1_desc', val2: '100% verified original luxury items' },
        { key1: 'feature2_title', val1: 'Bespoke Packaging', key2: 'feature2_desc', val2: 'Presented in signature handcrafted gift boxes' },
        { key1: 'feature3_title', val1: 'White-Glove Delivery', key2: 'feature3_desc', val2: 'Insured premium doorstep courier service' },
        { key1: 'feature4_title', val1: 'Lifetime Warranty', key2: 'feature4_desc', val2: 'Full coverage on craftsmanship and precision' },
      ]
    },
    defaultColors: { primary: '#8B5CF6', banner: '#13111C', bg: '#07090E', text: '#F8FAFC' },
    defaultFont: 'Plus Jakarta Sans',
  },

  emerald: {
    id: 'emerald',
    name: 'Verdant Organics',
    tagline: 'Deep forest green botanical & organic wellness aesthetic',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Organic Certified Tag',
      badgeDefault: '100% ORGANIC & ETHICAL HARVEST',
      hasHeadline: true,
      headlineLabel: 'Apothecary / Brand Name',
      hasSubtitle: true,
      subtitleLabel: 'Botanical Philosophy',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Apothecary CTA Button',
      ctaPrimaryDefault: 'Shop Herbal Blends ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Botanical Nature Hero Banner', desc: 'Organic herbs and wellness botanical image', default: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Catalog Section Title',
      catalogTitleDefault: 'Apothecary Formulary & Botanicals',
    },
    features: {
      hasFeaturesBanner: true,
      bannerTitle: '4 Botanical Guarantees',
      defaultCards: [
        { key1: 'feature1_title', val1: 'Zero Pesticides', key2: 'feature1_desc', val2: 'Pure organically sourced botanical harvests' },
        { key1: 'feature2_title', val1: 'Cruelty Free', key2: 'feature2_desc', val2: 'Never tested on animals, 100% vegan' },
        { key1: 'feature3_title', val1: 'Eco Packaging', key2: 'feature3_desc', val2: 'Biodegradable and recyclable glass packaging' },
        { key1: 'feature4_title', val1: 'Holistic Care', key2: 'feature4_desc', val2: 'Formulated by certified herbal practitioners' },
      ]
    },
    defaultColors: { primary: '#059669', banner: '#064E3B', bg: '#F2FBF6', text: '#064E3B' },
    defaultFont: 'Cormorant Garamond',
  },

  royal: {
    id: 'royal',
    name: 'Velvet Royalty',
    tagline: 'Imperial velvet palette with polished gold accents',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Maison Heritage Tag',
      badgeDefault: 'HAUTE HORLOGERIE & JOAILLERIE',
      hasHeadline: true,
      headlineLabel: 'Imperial Title / Maison Name',
      hasSubtitle: true,
      subtitleLabel: 'Prestige Statement',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Acquisition Button',
      ctaPrimaryDefault: 'Acquire Collection ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Imperial Jewelry Showcase Photo', desc: 'Prestige gemstone / timepiece image', default: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Treasury Section Title',
      catalogTitleDefault: 'The Imperial Treasury & Archive',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#D4AF37', banner: '#1A0B2E', bg: '#0A0512', text: '#FDF6E2' },
    defaultFont: 'Cinzel',
  },

  boho: {
    id: 'boho',
    name: 'Terracotta Earth',
    tagline: 'Warm clay, sun-baked terracotta, and artisanal ceramics',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Studio Badge',
      badgeDefault: 'HAND-THROWN IN SMALL BATCHES',
      hasHeadline: true,
      headlineLabel: 'Ceramic Studio Name',
      hasSubtitle: true,
      subtitleLabel: 'Craft Philosophy',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Pottery CTA Button',
      ctaPrimaryDefault: 'Explore Pottery ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Handcrafted Pottery Hero Photo', desc: 'Warm clay ceramics image', default: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Studio Catalog Title',
      catalogTitleDefault: 'Studio Ceramic Pieces',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#C2410C', banner: '#7C2D12', bg: '#FAF5EF', text: '#431407' },
    defaultFont: 'Playfair Display',
  },

  popart: {
    id: 'popart',
    name: 'Vibrant Pop Art',
    tagline: 'Electric yellow and hot pink comic neobrutalism layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Drop Badge Label',
      badgeDefault: '?? LIMITED EDITION DROPS',
      hasHeadline: true,
      headlineLabel: 'Pop Brand Title',
      hasSubtitle: true,
      subtitleLabel: 'Comic Tagline',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Action CTA Button',
      ctaPrimaryDefault: 'GRAB IT NOW! ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Comic Pop Visual Art Card', desc: 'Vibrant pop art collectible showcase image', default: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Vault Title',
      catalogTitleDefault: '/// POP CULTURE VAULT',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#FACC15', banner: '#EC4899', bg: '#FEF08A', text: '#000000' },
    defaultFont: 'Montserrat',
  },

  retro: {
    id: 'retro',
    name: 'Vintage 70s Vinyl',
    tagline: 'Groovy 1970s warm mustard and burnt orange analog aesthetic',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Vinyl Heritage Tag',
      badgeDefault: 'EST. 1974 // ANALOG SOUNDS & GEAR',
      hasHeadline: true,
      headlineLabel: 'Record Store / Brand Name',
      hasSubtitle: true,
      subtitleLabel: 'Vintage Catchphrase',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Crate Digging Button',
      ctaPrimaryDefault: 'Start Crate Digging ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Vintage Vinyl Turntable Image', desc: 'Warm 70s turntable or vintage gear photo', default: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Vinyl Section Title',
      catalogTitleDefault: '/// VINYL CRATE & RETRO GEAR',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#D97706', banner: '#78350F', bg: '#FFFBEB', text: '#451A03' },
    defaultFont: 'Playfair Display',
  },

  pastel: {
    id: 'pastel',
    name: 'Pastel Dreamscape',
    tagline: 'Soft lavender, peach, and marshmallow confectionery layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Gentle Glow Tag',
      badgeDefault: '?? SWEET & DELICATE FORMULAS',
      hasHeadline: true,
      headlineLabel: 'Pastel Store Name',
      hasSubtitle: true,
      subtitleLabel: 'Sweet Dream Catchphrase',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Dreamy Button Text',
      ctaPrimaryDefault: 'Discover The Glow ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Pastel Beauty / Bakery Image', desc: 'Soft pastel confectionery or beauty photo', default: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Catalog Title',
      catalogTitleDefault: 'Pastel Confections & Beauty',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#F472B6', banner: '#C084FC', bg: '#FDF4FF', text: '#701A75' },
    defaultFont: 'Pacifico',
  },

  industrial: {
    id: 'industrial',
    name: 'Industrial Workshop',
    tagline: 'Heavy-duty steel, carbon slate, and warning amber machinery',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Specification Badge',
      badgeDefault: '// HEAVY DUTY INDUSTRIAL SPECS',
      hasHeadline: true,
      headlineLabel: 'Workshop Name',
      hasSubtitle: true,
      subtitleLabel: 'Engineering Manifesto',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Machinery Button',
      ctaPrimaryDefault: 'Inspect Machinery ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Industrial Machinery Gear Photo', desc: 'Precision tools and heavy gear hero image', default: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Hardware Title',
      catalogTitleDefault: '// HARDWARE & TOOL CATALOGUE',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#F59E0B', banner: '#1F2937', bg: '#111827', text: '#F3F4F6' },
    defaultFont: 'Space Grotesk',
  },

  zenith: {
    id: 'zenith',
    name: 'Zenith Modern',
    tagline: 'High performance data-driven SaaS & enterprise storefront',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Enterprise Badge',
      badgeDefault: 'ENTERPRISE SCALE ECOSYSTEM',
      hasHeadline: true,
      headlineLabel: 'Platform Title',
      hasSubtitle: true,
      subtitleLabel: 'Solution Tagline',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Solutions CTA',
      ctaPrimaryDefault: 'Explore Solutions ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Tech Hardware & Device Photo', desc: 'Clean high-performance device showcase image', default: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Inventory Heading',
      catalogTitleDefault: 'Product Inventory & Solutions',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#4F46E5', banner: '#1E293B', bg: '#0F172A', text: '#E2E8F0' },
    defaultFont: 'Inter',
  },

  monochrome: {
    id: 'monochrome',
    name: 'Monochrome Dark',
    tagline: 'Ultra-contrast black & white gallery aesthetic',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Noir Edition Tag',
      badgeDefault: 'NOIR COLLECTION // EDITION 01',
      hasHeadline: true,
      headlineLabel: 'Monochrome Brand Name',
      hasSubtitle: true,
      subtitleLabel: 'Minimalist Summary',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'View Index Button',
      ctaPrimaryDefault: 'View Catalog ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Noir Studio Visual Photo', desc: 'Monochrome high-contrast design photo', default: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Index Title',
      catalogTitleDefault: 'Curated Noir Index',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#FFFFFF', banner: '#18181B', bg: '#09090B', text: '#F4F4F5' },
    defaultFont: 'Outfit',
  },

  artisan: {
    id: 'artisan',
    name: 'The Artisan Gazette',
    tagline: 'Editorial broadsheet newspaper print layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Masthead Sub-Header Tag',
      badgeDefault: 'EST. 1892 // DAILY ARTISAN DISPATCH',
      hasHeadline: true,
      headlineLabel: 'Gazette Masthead Name',
      hasSubtitle: true,
      subtitleLabel: 'Editorial Opening Column',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Dispatch CTA Button',
      ctaPrimaryDefault: 'Read Classifieds ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Front Page Editorial Photo', desc: 'Vintage print or newspaper story photo', default: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Classifieds Title',
      catalogTitleDefault: 'Classifieds & Curated Goods',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#8B7355', banner: '#2D2D2D', bg: '#FBF8F0', text: '#2D2D2D' },
    defaultFont: 'Playfair Display',
  },

  futura: {
    id: 'futura',
    name: 'Futura Cyber Matrix',
    tagline: 'Sci-fi holographic HUD and neon cyan matrix grid',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'System Kernel Badge',
      badgeDefault: 'SYSTEM BOOT // V3.88 KERNEL ACTIVE',
      hasHeadline: true,
      headlineLabel: 'Matrix Station Name',
      hasSubtitle: true,
      subtitleLabel: 'Command Subtitle',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Matrix CTA Button',
      ctaPrimaryDefault: 'Initialize Matrix ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Holographic Matrix Visual', desc: 'Cyber futuristic matrix hero render', default: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Matrix Title',
      catalogTitleDefault: 'Cybernetic Device Matrix',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#00F0FF', banner: '#030712', bg: '#020617', text: '#38BDF8' },
    defaultFont: 'Space Grotesk',
  },

  lookbook: {
    id: 'lookbook',
    name: 'Editorial Lookbook',
    tagline: 'High-fashion runway and editorial haute couture layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Season Runway Tag',
      badgeDefault: 'AUTUMN / WINTER EDITORIAL LOOKBOOK',
      hasHeadline: true,
      headlineLabel: 'Fashion House / Brand Title',
      hasSubtitle: true,
      subtitleLabel: 'Runway Statement',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Lookbook CTA Button',
      ctaPrimaryDefault: 'View Lookbook ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Runway High Fashion Image', desc: 'Haute couture editorial model photo', default: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Collection Title',
      catalogTitleDefault: 'Runway Capsule Collection',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#FFFFFF', banner: '#111827', bg: '#000000', text: '#F3F4F6' },
    defaultFont: 'Syne',
  },

  bazaar: {
    id: 'bazaar',
    name: 'Bazaar Marketplace',
    tagline: 'Multi-category marketplace with category pills and badges',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Marketplace Verification Tag',
      badgeDefault: '100% VERIFIED SELLERS & ESCROW SECURE',
      hasHeadline: true,
      headlineLabel: 'Marketplace Name',
      hasSubtitle: true,
      subtitleLabel: 'Marketplace Slogan',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Browse Button',
      ctaPrimaryDefault: 'Browse Marketplace ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Marketplace Banner / Hero Image', desc: 'Wide banner showcase visual', default: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Categories Title',
      catalogTitleDefault: 'Marketplace Goods & Stalls',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#FF6B35', banner: '#FF6B35', bg: '#F7F7F7', text: '#333333' },
    defaultFont: 'Inter',
  },

  timeline: {
    id: 'timeline',
    name: 'Museum Archive',
    tagline: 'Curatorial museum artifact archive and exhibition layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Exhibition Hall Badge',
      badgeDefault: 'PERMANENT CURATORIAL EXHIBITION',
      hasHeadline: true,
      headlineLabel: 'Museum / Archive Title',
      hasSubtitle: true,
      subtitleLabel: 'Curatorial Foreword',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Exhibition Tour Button',
      ctaPrimaryDefault: 'Tour Archive ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Historical Artifact Hero Image', desc: 'Museum sculpture or relic artifact photo', default: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Exhibition Section Title',
      catalogTitleDefault: 'Permanent Exhibition & Artifacts',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#C9A84C', banner: '#1C1917', bg: '#0C0A09', text: '#E7E5E4' },
    defaultFont: 'Cinzel',
  },

  department: {
    id: 'department',
    name: 'Department Store',
    tagline: 'Traditional multi-aisle retail department store',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Storefront Service Tag',
      badgeDefault: 'PREMIER RETAIL DEPARTMENT STORE',
      hasHeadline: true,
      headlineLabel: 'Department Store Name',
      hasSubtitle: true,
      subtitleLabel: 'Store Catchphrase',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Aisles CTA Button',
      ctaPrimaryDefault: 'Shop Department ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Department Retail Banner Image', desc: 'Clean department store showroom photo', default: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Aisles Section Title',
      catalogTitleDefault: 'Department Catalog & Aisles',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#1B3A5C', banner: '#1B3A5C', bg: '#FFFFFF', text: '#333333' },
    defaultFont: 'Inter',
  },

  polaroid: {
    id: 'polaroid',
    name: 'Polaroid Memories',
    tagline: 'Nostalgic instant polaroid photo snap album layout',
    hero: {
      hasWelcomePrefix: false,
      hasBadge: true,
      badgeLabel: 'Film Snap Tag',
      badgeDefault: 'INSTANT MEMORIES & HANDMADE SNAPS',
      hasHeadline: true,
      headlineLabel: 'Polaroid Studio Title',
      hasSubtitle: true,
      subtitleLabel: 'Nostalgia Catchphrase',
      hasCtaPrimary: true,
      ctaPrimaryLabel: 'Flip Album Button',
      ctaPrimaryDefault: 'Flip Memories ?',
      hasCtaSecondary: false,
      imageSlots: [
        { key: 'hero_image_1', label: 'Featured Polaroid Photo Snap', desc: 'Instant film polaroid print photo', default: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=700&q=80' },
      ],
    },
    sections: {
      hasFeaturedTitle: false,
      hasCatalogTitle: true,
      catalogTitleLabel: 'Snaps Title',
      catalogTitleDefault: 'Instant Polaroid Photo Snaps',
    },
    features: { hasFeaturesBanner: false },
    defaultColors: { primary: '#8B6F55', banner: '#4A3728', bg: '#FAF6F0', text: '#4A3728' },
    defaultFont: 'Caveat',
  },
}

export function getTemplateSchema(templateId) {
  return TEMPLATE_CUSTOMIZATION_SCHEMAS[templateId] || TEMPLATE_CUSTOMIZATION_SCHEMAS.honeyspicy
}
