# Generated by Django 5.0.1 on 2026-07-10 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_ids', models.JSONField(default=list)),
                ('shop_ids', models.JSONField(default=list)),
                ('affinities_snapshot', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'recommendation caches',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('product', 'Product'), ('shop', 'Shop')], db_index=True, max_length=16)),
                ('target_id', models.PositiveBigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'target_type'], name='personaliza_user_id_212199_idx')],
                'unique_together': {('user', 'target_type', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='PersonalizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_view', 'Product view'), ('product_click', 'Product click'), ('shop_view', 'Shop view'), ('search', 'Search'), ('add_to_cart', 'Add to cart'), ('remove_from_cart', 'Remove from cart'), ('purchase', 'Purchase'), ('favourite', 'Favourite'), ('unfavourite', 'Unfavourite'), ('review', 'Review')], db_index=True, max_length=24)),
                ('target_type', models.CharField(db_index=True, help_text="'product', 'shop', or 'category'.", max_length=16)),
                ('target_id', models.PositiveBigIntegerField(help_text='PK of the target product, shop, or category.')),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('category_slug', models.CharField(blank=True, max_length=140)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('device_type', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalization_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'event_type', '-created_at'], name='personaliza_user_id_e170b9_idx'), models.Index(fields=['target_type', 'target_id'], name='personaliza_target__32d3f9_idx'), models.Index(fields=['user', '-created_at'], name='personaliza_user_id_4a88c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_result_id', models.PositiveBigIntegerField(blank=True, help_text='PK of the product/shop the user clicked from results.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='personaliza_user_id_c81fac_idx')],
            },
        ),
    ]
