# Generated by Django 5.0.1 on 2026-09-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_twofactorauth'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when account was deactivated/soft-deleted. Preserved for fraud/legal audits.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', help_text='Reason recorded when the account was deactivated.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='accounts_us_deleted_08a5c0_idx'),
        ),
    ]
