# Generated by Django 5.0.1 on 2026-07-18 11:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(help_text="Stable machine identifier, e.g. 'free', 'growth'.", max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Recurring monthly price in the plan currency.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('max_shops', models.PositiveIntegerField(blank=True, help_text='Maximum shops the user may own. Blank/NULL = unlimited.', null=True)),
                ('max_products', models.PositiveIntegerField(blank=True, help_text="Maximum products across all the user's shops. Blank/NULL = unlimited.", null=True)),
                ('custom_domain_enabled', models.BooleanField(default=False)),
                ('analytics_enabled', models.BooleanField(default=False)),
                ('staff_accounts_enabled', models.BooleanField(default=False)),
                ('priority_support_enabled', models.BooleanField(default=False)),
                ('is_enterprise', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive plans are hidden from pricing and cannot be subscribed to (existing subscribers keep their plan).')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ascending sort order on the pricing page.')),
            ],
            options={
                'ordering': ('display_order', 'monthly_price'),
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='subscriptio_is_acti_c2a27e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_subscription_code', models.CharField(blank=True, max_length=255)),
                ('provider_customer_code', models.CharField(blank=True, max_length=255)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_28ce5e_idx'), models.Index(fields=['status', 'end_date'], name='subscriptio_status_93cc56_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='uniq_active_subscription_per_user'),
        ),
    ]
