# Generated by Django 5.0.1 on 2026-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_default_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='premium_templates_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
