# Generated by Django 5.0.1 on 2026-08-23 16:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_premium_templates_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(db_index=True, help_text="Unique coupon code, e.g. 'LAUNCH100', 'PROMO50', 'GROWTHFREE'.", max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount (₦)')], default='percentage', max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Discount value (e.g. 100 for 100% free trial, 50 for 50% off, or 5000 for ₦5,000 off).', max_digits=10)),
                ('duration_months', models.PositiveIntegerField(default=1, help_text='Number of free/discounted subscription months granted (e.g. 1, 3, 12). 0 = perpetual/lifetime.')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum total redemptions allowed. Leave blank for unlimited.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Total number of times this coupon has been successfully redeemed.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date. Leave blank for no expiration.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this coupon is currently active.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscription_coupons', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text='Specific subscription tier this coupon applies to. Leave empty for All Tiers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('duration_months_granted', models.PositiveIntegerField(default=1)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='subscriptions.subscriptioncoupon')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='subscriptions.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
