# Generated by Django 5.0.1 on 2026-08-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptioncoupon_subscriptioncouponredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_shop_template_enabled',
            field=models.BooleanField(default=False, help_text='Unlock access to all 20 premium storefront templates.', verbose_name='Custom shop template enabled'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_shop_theme_enabled',
            field=models.BooleanField(default=False, help_text='Unlock theme customizer, hero banner edits, color tokens, and layout styles.', verbose_name='Custom shop theme enabled'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='analytics_enabled',
            field=models.BooleanField(default=False, help_text='Enable sales, revenue, and customer traffic analytics.', verbose_name='Analytics enabled'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='custom_domain_enabled',
            field=models.BooleanField(default=False, help_text='Allow linking custom .com / .ng domains to shop.', verbose_name='Custom shop domain enabled'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='priority_support_enabled',
            field=models.BooleanField(default=False, help_text='Grant 24/7 priority support queue.', verbose_name='Priority support enabled'),
        ),
    ]
