# Generated by Django 5.0.1 on 2026-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='referralcode',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='referralearning',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='referralearning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
