import os
import sys

def fix_migration_history():
    db_url = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL") or os.environ.get("DATABASE_PRIVATE_URL")
    if not db_url:
        pghost = os.environ.get("PGHOST")
        pguser = os.environ.get("PGUSER", "postgres")
        pgpass = os.environ.get("PGPASSWORD", "")
        pgdb = os.environ.get("PGDATABASE")
        pgport = os.environ.get("PGPORT", "5432")
        if pghost and pgdb:
            db_url = f"postgresql://{pguser}:{pgpass}@{pghost}:{pgport}/{pgdb}"

    if not db_url:
        print("No PostgreSQL connection string found. Skipping raw SQL migration fix.")
        return

    try:
        import psycopg2
        conn = psycopg2.connect(db_url)
        conn.autocommit = True
        cursor = conn.cursor()

        # Ensure django_migrations table exists
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS django_migrations (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                app character varying(255) NOT NULL,
                name character varying(255) NOT NULL,
                applied timestamp with time zone NOT NULL
            );
        """)

        # Ensure unique index on (app, name)
        cursor.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS django_migrations_app_name_uniq 
            ON django_migrations (app, name);
        """)

        # Populate core migration history to satisfy custom user model dependency chain
        sql = """
            INSERT INTO django_migrations (app, name, applied)
            VALUES
            ('contenttypes', '0001_initial', CURRENT_TIMESTAMP),
            ('contenttypes', '0002_touch_inconsistent_content_types', CURRENT_TIMESTAMP),
            ('auth', '0001_initial', CURRENT_TIMESTAMP),
            ('auth', '0002_alter_permission_name_max_length', CURRENT_TIMESTAMP),
            ('auth', '0003_alter_user_email_max_length', CURRENT_TIMESTAMP),
            ('auth', '0004_alter_user_username_opts', CURRENT_TIMESTAMP),
            ('auth', '0005_alter_user_last_login_null', CURRENT_TIMESTAMP),
            ('auth', '0006_require_contenttypes_0002', CURRENT_TIMESTAMP),
            ('auth', '0007_alter_validators_add_error_messages', CURRENT_TIMESTAMP),
            ('auth', '0008_alter_user_username_max_length', CURRENT_TIMESTAMP),
            ('auth', '0009_alter_user_last_name_max_length', CURRENT_TIMESTAMP),
            ('auth', '0010_alter_group_name_max_length', CURRENT_TIMESTAMP),
            ('auth', '0011_update_proxy_permissions', CURRENT_TIMESTAMP),
            ('auth', '0012_alter_user_first_name_max_length', CURRENT_TIMESTAMP),
            ('accounts', '0001_initial', CURRENT_TIMESTAMP)
            ON CONFLICT (app, name) DO NOTHING;
        """
        cursor.execute(sql)
        print("==> Pre-populated core migration history in PostgreSQL successfully.")
        cursor.close()
        conn.close()
    except Exception as e:
        print(f"==> Direct database pre-population note: {e}")

if __name__ == "__main__":
    fix_migration_history()
